//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pinula.API.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App_cs {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App_cs() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Pinula.API.Resources.App_cs", typeof(App_cs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EmailSubject_Registration {
            get {
                return ResourceManager.GetString("EmailSubject_Registration", resourceCulture);
            }
        }
        
        internal static string EmailSubject_PasswordReset {
            get {
                return ResourceManager.GetString("EmailSubject_PasswordReset", resourceCulture);
            }
        }
        
        internal static string EmailSubject_EmailChange {
            get {
                return ResourceManager.GetString("EmailSubject_EmailChange", resourceCulture);
            }
        }
        
        internal static string EmailSubject_SensitiveAction {
            get {
                return ResourceManager.GetString("EmailSubject_SensitiveAction", resourceCulture);
            }
        }
        
        internal static string EmailSubject_Default {
            get {
                return ResourceManager.GetString("EmailSubject_Default", resourceCulture);
            }
        }
        
        internal static string ActionName_Registration {
            get {
                return ResourceManager.GetString("ActionName_Registration", resourceCulture);
            }
        }
        
        internal static string ActionName_PasswordReset {
            get {
                return ResourceManager.GetString("ActionName_PasswordReset", resourceCulture);
            }
        }
        
        internal static string ActionName_EmailChange {
            get {
                return ResourceManager.GetString("ActionName_EmailChange", resourceCulture);
            }
        }
        
        internal static string ActionName_Default {
            get {
                return ResourceManager.GetString("ActionName_Default", resourceCulture);
            }
        }
        
        internal static string EmailTemplate_Title {
            get {
                return ResourceManager.GetString("EmailTemplate_Title", resourceCulture);
            }
        }
        
        internal static string EmailTemplate_BodyPrefix {
            get {
                return ResourceManager.GetString("EmailTemplate_BodyPrefix", resourceCulture);
            }
        }
        
        internal static string EmailTemplate_Validity {
            get {
                return ResourceManager.GetString("EmailTemplate_Validity", resourceCulture);
            }
        }
        
        internal static string EmailTemplate_Rights {
            get {
                return ResourceManager.GetString("EmailTemplate_Rights", resourceCulture);
            }
        }
    }
}
