// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pinula.API.Context;

#nullable disable

namespace Pinula.API.Migrations
{
    [DbContext(typeof(CookRecipesDbContext))]
    [Migration("20260523092728_AddModeration")]
    partial class AddModeration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pinula.Shared.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategory")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("picture_url")
                        .HasDefaultValueSql("'default_category_picture.png'::text");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("categories_pkey");

                    b.HasIndex("ParentCategory");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_approved");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<short?>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("comments_pkey");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Calories")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("calories");

                    b.Property<decimal>("Carbohydrates")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("carbohydrates");

                    b.Property<Guid>("DefaultUnit")
                        .HasColumnType("uuid")
                        .HasColumnName("default_unit");

                    b.Property<decimal>("Fats")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("fats");

                    b.Property<decimal>("Fiber")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("fiber");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Proteins")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("proteins");

                    b.HasKey("Id")
                        .HasName("ingredients_pkey");

                    b.HasIndex("DefaultUnit");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.IngredientUnit", b =>
                {
                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal>("ToDefaultUnit")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("to_default_unit");

                    b.HasKey("UnitId", "IngredientId")
                        .HasName("ingredientUnits_pkey");

                    b.HasIndex("IngredientId");

                    b.ToTable("ingredientUnits", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Calories")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("calories");

                    b.Property<decimal?>("Carbohydrates")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("carbohydrates");

                    b.Property<short>("CookingTime")
                        .HasColumnType("smallint")
                        .HasColumnName("cooking_time");

                    b.Property<short>("Difficulty")
                        .HasColumnType("smallint")
                        .HasColumnName("difficulty");

                    b.Property<decimal?>("Fats")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("fats");

                    b.Property<decimal?>("Fiber")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("fiber");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_approved");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("photo_url")
                        .HasDefaultValueSql("'default_recipe_picture.png'::text");

                    b.Property<decimal?>("Proteins")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("proteins");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("rating");

                    b.Property<DateTime>("RecipeCreated")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("recipe_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ServingUnit")
                        .HasColumnType("uuid")
                        .HasColumnName("serving_unit");

                    b.Property<short>("ServingsAmount")
                        .HasColumnType("smallint")
                        .HasColumnName("servings_amount");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("UsersRated")
                        .HasColumnType("integer")
                        .HasColumnName("users_rated");

                    b.HasKey("Id")
                        .HasName("recipes_pkey");

                    b.HasIndex("ServingUnit");

                    b.HasIndex("UserId");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal?>("ConversionFactor")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("conversion_factor");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("RecipeId", "IngredientId")
                        .HasName("recipeIngredients_pkey");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UnitId");

                    b.ToTable("recipeIngredients", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.RecipeStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<short>("StepNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("step_number");

                    b.HasKey("Id")
                        .HasName("recipeSteps_pkey");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipeSteps", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.RecipesUser", b =>
                {
                    b.Property<Guid>("RecipesId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipes_id");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid")
                        .HasColumnName("users_id");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("isFavorite");

                    b.HasKey("RecipesId", "UsersId")
                        .HasName("recipes_users_pkey");

                    b.HasIndex("UsersId");

                    b.ToTable("recipes_users", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsServingUnit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_serving_unit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("units_pkey");

                    b.HasIndex(new[] { "Name" }, "units_name_key")
                        .IsUnique();

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("avatar_url")
                        .HasDefaultValueSql("'default_avatar.png'::text");

                    b.Property<bool>("CanComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_comment");

                    b.Property<bool>("CanCreateRecipes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_create_recipes");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'user'::text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.Property<DateTime>("UserCreated")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("user_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RecipeCategory", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("RecipeId", "CategoryId")
                        .HasName("recipeCategories_pkey");

                    b.HasIndex("CategoryId");

                    b.ToTable("recipeCategories", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.Category", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Category", "ParentCategoryNavigation")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategory")
                        .HasConstraintName("categories_parent_category_fkey");

                    b.Navigation("ParentCategoryNavigation");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Comment", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("comments_parent_fkey");

                    b.HasOne("Pinula.Shared.Models.Recipe", "Recipe")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("comments_recipe_id_fkey");

                    b.HasOne("Pinula.Shared.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("comments_user_id_fkey");

                    b.Navigation("ParentComment");

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Ingredient", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Unit", "DefaultUnitNavigation")
                        .WithMany("Ingredients")
                        .HasForeignKey("DefaultUnit")
                        .IsRequired()
                        .HasConstraintName("ingredients_default_unit_fkey");

                    b.Navigation("DefaultUnitNavigation");
                });

            modelBuilder.Entity("Pinula.Shared.Models.IngredientUnit", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Ingredient", "Ingredient")
                        .WithMany("IngredientUnits")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("ingredientUnits_ingredient_id_fkey");

                    b.HasOne("Pinula.Shared.Models.Unit", "Unit")
                        .WithMany("IngredientUnits")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("ingredientUnits_unit_id_fkey");

                    b.Navigation("Ingredient");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Recipe", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Unit", "ServingUnitNavigation")
                        .WithMany("Recipes")
                        .HasForeignKey("ServingUnit")
                        .IsRequired()
                        .HasConstraintName("recipes_serving_unit_fkey");

                    b.HasOne("Pinula.Shared.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("recipes_user_id_fkey");

                    b.Navigation("ServingUnitNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pinula.Shared.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("recipeIngredients_ingredient_id_fkey");

                    b.HasOne("Pinula.Shared.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("recipeIngredients_recipe_id_fkey");

                    b.HasOne("Pinula.Shared.Models.Unit", "Unit")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("recipeIngredients_unit_id_fkey");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Pinula.Shared.Models.RecipeStep", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Recipe", "Recipe")
                        .WithMany("RecipeSteps")
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("recipeSteps_recipe_id_fkey");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Pinula.Shared.Models.RecipesUser", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Recipe", "Recipes")
                        .WithMany("RecipesUsers")
                        .HasForeignKey("RecipesId")
                        .IsRequired()
                        .HasConstraintName("recipes_users_recipes_id_fkey");

                    b.HasOne("Pinula.Shared.Models.User", "Users")
                        .WithMany("RecipesUsers")
                        .HasForeignKey("UsersId")
                        .IsRequired()
                        .HasConstraintName("recipes_users_users_id_fkey");

                    b.Navigation("Recipes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RecipeCategory", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("recipeCategories_category_id_fkey");

                    b.HasOne("Pinula.Shared.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("recipeCategories_recipe_id_fkey");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Category", b =>
                {
                    b.Navigation("ChildCategories");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Ingredient", b =>
                {
                    b.Navigation("IngredientUnits");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Recipe", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("RecipeSteps");

                    b.Navigation("RecipesUsers");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Unit", b =>
                {
                    b.Navigation("IngredientUnits");

                    b.Navigation("Ingredients");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Pinula.Shared.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Recipes");

                    b.Navigation("RecipesUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
