// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pinula.API.Context;

#nullable disable

namespace Pinula.API.Migrations
{
    [DbContext(typeof(PinulaDbContext))]
    [Migration("20260625094143_EdibleRatioAddedToIngredientSystem")]
    partial class EdibleRatioAddedToIngredientSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("categories_id");

                    b.Property<Guid>("RecipesId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipes_id");

                    b.HasKey("CategoriesId", "RecipesId")
                        .HasName("pk_category_recipe");

                    b.HasIndex("RecipesId")
                        .HasDatabaseName("ix_category_recipe_recipes_id");

                    b.ToTable("category_recipe", (string)null);
                });

            modelBuilder.Entity("MealPlanUser", b =>
                {
                    b.Property<Guid>("MealPlansId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_plans_id");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid")
                        .HasColumnName("users_id");

                    b.HasKey("MealPlansId", "UsersId")
                        .HasName("pk_meal_plan_user");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_meal_plan_user_users_id");

                    b.ToTable("meal_plan_user", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Dictionary<string, string>>("Names")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("names");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("default_category_picture.png")
                        .HasColumnName("picture_url");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_categories_parent_category_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_approved");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_edited");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<short?>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_comments_parent_comment_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_comments_recipe_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comments_user_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("invite_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<Guid?>("BaseIngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_ingredient_id");

                    b.Property<decimal>("Calories")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("calories");

                    b.Property<decimal>("Carbohydrates")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("carbohydrates");

                    b.Property<Guid>("DefaultUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_unit_id");

                    b.Property<decimal?>("EdibleRatio")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("edible_ratio");

                    b.Property<decimal>("Fats")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("fats");

                    b.Property<decimal>("Fiber")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("fiber");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsGlutenFree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_gluten_free");

                    b.Property<bool>("IsLactoseFree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_lactose_free");

                    b.Property<bool>("IsVegan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_vegan");

                    b.Property<bool>("IsVegetarian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_vegetarian");

                    b.Property<Dictionary<string, string>>("Names")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("names");

                    b.Property<int?>("NovaClassification")
                        .HasColumnType("integer")
                        .HasColumnName("nova_classification");

                    b.Property<string>("NutriScore")
                        .HasColumnType("text")
                        .HasColumnName("nutri_score");

                    b.Property<string>("OffCategoryTag")
                        .HasColumnType("text")
                        .HasColumnName("off_category_tag");

                    b.Property<decimal>("Proteins")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("proteins");

                    b.Property<decimal>("Salt")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("salt");

                    b.Property<decimal>("SaturatedFats")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("saturated_fats");

                    b.Property<Guid>("ShoppingCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_category_id");

                    b.Property<decimal>("Sugars")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("sugars");

                    b.HasKey("Id")
                        .HasName("pk_ingredients");

                    b.HasIndex("BaseIngredientId")
                        .HasDatabaseName("ix_ingredients_base_ingredient_id");

                    b.HasIndex("DefaultUnitId")
                        .HasDatabaseName("ix_ingredients_default_unit_id");

                    b.HasIndex("ShoppingCategoryId")
                        .HasDatabaseName("ix_ingredients_shopping_category_id");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.IngredientUnit", b =>
                {
                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal>("AmountInGrams")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("amount_in_grams");

                    b.HasKey("UnitId", "IngredientId")
                        .HasName("pk_ingredient_units");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_ingredient_units_ingredient_id");

                    b.ToTable("ingredient_units", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int>("MealType")
                        .HasColumnType("integer")
                        .HasColumnName("meal_type");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<int>("Servings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("servings");

                    b.HasKey("Id")
                        .HasName("pk_meal_plans");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_meal_plans_group_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_meal_plans_recipe_id");

                    b.ToTable("meal_plans", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Calories")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("calories");

                    b.Property<decimal?>("Carbohydrates")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("carbohydrates");

                    b.Property<short>("CookingTime")
                        .HasColumnType("smallint")
                        .HasColumnName("cooking_time");

                    b.Property<short>("Difficulty")
                        .HasColumnType("smallint")
                        .HasColumnName("difficulty");

                    b.Property<decimal?>("Fats")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("fats");

                    b.Property<decimal?>("Fiber")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("fiber");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_approved");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_language");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<decimal?>("Proteins")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("proteins");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("rating");

                    b.Property<DateTime>("RecipeCreated")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("recipe_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ServingUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("serving_unit_id");

                    b.Property<short>("ServingsAmount")
                        .HasColumnType("smallint")
                        .HasColumnName("servings_amount");

                    b.Property<Dictionary<string, string>>("Titles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("titles");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("UsersRated")
                        .HasColumnType("integer")
                        .HasColumnName("users_rated");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.HasIndex("ServingUnitId")
                        .HasDatabaseName("ix_recipes_serving_unit_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_recipes_user_id");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal?>("ConversionFactor")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("conversion_factor");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("RecipeId", "IngredientId")
                        .HasName("pk_recipe_ingredients");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_recipe_ingredients_ingredient_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_recipe_ingredients_unit_id");

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.RecipeStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Dictionary<string, string>>("Descriptions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("descriptions");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<short>("StepNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("step_number");

                    b.HasKey("Id")
                        .HasName("pk_recipe_steps");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_recipe_steps_recipe_id");

                    b.ToTable("recipe_steps", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.RecipeUser", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.HasKey("RecipeId", "UserId")
                        .HasName("pk_recipe_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_recipe_users_user_id");

                    b.ToTable("recipe_users", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.ShoppingCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<Dictionary<string, string>>("Names")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("names");

                    b.HasKey("Id")
                        .HasName("pk_shopping_categories");

                    b.ToTable("shopping_categories", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<bool>("IsServingUnit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_serving_unit");

                    b.Property<Dictionary<string, string>>("Names")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("names");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_units_code");

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("Pinula.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("default_avatar.png")
                        .HasColumnName("avatar_url");

                    b.Property<bool>("CanComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_comment");

                    b.Property<bool>("CanCreateRecipes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_create_recipes");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.Property<DateTime>("UserCreated")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("user_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_users_group_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_recipe_categories_categories_id");

                    b.HasOne("Pinula.Shared.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_recipe_recipes_recipes_id");
                });

            modelBuilder.Entity("MealPlanUser", b =>
                {
                    b.HasOne("Pinula.Shared.Models.MealPlan", null)
                        .WithMany()
                        .HasForeignKey("MealPlansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meal_plan_user_meal_plans_meal_plans_id");

                    b.HasOne("Pinula.Shared.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meal_plan_user_users_users_id");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Category", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .HasConstraintName("fk_categories_categories_parent_category_id");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Comment", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_comments_comments_parent_comment_id");

                    b.HasOne("Pinula.Shared.Models.Recipe", "Recipe")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("fk_comments_recipes_recipe_id");

                    b.HasOne("Pinula.Shared.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_user_id");

                    b.Navigation("ParentComment");

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Ingredient", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Ingredient", "BaseIngredient")
                        .WithMany("BrandedProducts")
                        .HasForeignKey("BaseIngredientId")
                        .HasConstraintName("fk_ingredients_ingredients_base_ingredient_id");

                    b.HasOne("Pinula.Shared.Models.Unit", "DefaultUnit")
                        .WithMany("Ingredients")
                        .HasForeignKey("DefaultUnitId")
                        .IsRequired()
                        .HasConstraintName("fk_ingredients_units_default_unit_id");

                    b.HasOne("Pinula.Shared.Models.ShoppingCategory", "ShoppingCategory")
                        .WithMany("Ingredients")
                        .HasForeignKey("ShoppingCategoryId")
                        .IsRequired()
                        .HasConstraintName("fk_ingredients_shopping_categories_shopping_category_id");

                    b.Navigation("BaseIngredient");

                    b.Navigation("DefaultUnit");

                    b.Navigation("ShoppingCategory");
                });

            modelBuilder.Entity("Pinula.Shared.Models.IngredientUnit", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Ingredient", "Ingredient")
                        .WithMany("IngredientUnits")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_units_ingredients_ingredient_id");

                    b.HasOne("Pinula.Shared.Models.Unit", "Unit")
                        .WithMany("IngredientUnits")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_units_units_unit_id");

                    b.Navigation("Ingredient");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Pinula.Shared.Models.MealPlan", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Group", "Group")
                        .WithMany("MealPlans")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meal_plans_groups_group_id");

                    b.HasOne("Pinula.Shared.Models.Recipe", "Recipe")
                        .WithMany("MealPlans")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meal_plans_recipes_recipe_id");

                    b.Navigation("Group");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Recipe", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Unit", "ServingUnit")
                        .WithMany("Recipes")
                        .HasForeignKey("ServingUnitId")
                        .IsRequired()
                        .HasConstraintName("fk_recipes_units_serving_unit_id");

                    b.HasOne("Pinula.Shared.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_recipes_users_user_id");

                    b.Navigation("ServingUnit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pinula.Shared.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_ingredients_ingredient_id");

                    b.HasOne("Pinula.Shared.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_recipes_recipe_id");

                    b.HasOne("Pinula.Shared.Models.Unit", "Unit")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_units_unit_id");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Pinula.Shared.Models.RecipeStep", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Recipe", "Recipe")
                        .WithMany("RecipeSteps")
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("fk_recipe_steps_recipes_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Pinula.Shared.Models.RecipeUser", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Recipe", "Recipes")
                        .WithMany("RecipeUsers")
                        .HasForeignKey("RecipeId")
                        .IsRequired()
                        .HasConstraintName("fk_recipe_users_recipes_recipe_id");

                    b.HasOne("Pinula.Shared.Models.User", "Users")
                        .WithMany("RecipeUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_recipe_users_users_user_id");

                    b.Navigation("Recipes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Pinula.Shared.Models.User", b =>
                {
                    b.HasOne("Pinula.Shared.Models.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Category", b =>
                {
                    b.Navigation("ChildCategories");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Group", b =>
                {
                    b.Navigation("MealPlans");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Ingredient", b =>
                {
                    b.Navigation("BrandedProducts");

                    b.Navigation("IngredientUnits");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Recipe", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("MealPlans");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("RecipeSteps");

                    b.Navigation("RecipeUsers");
                });

            modelBuilder.Entity("Pinula.Shared.Models.ShoppingCategory", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Pinula.Shared.Models.Unit", b =>
                {
                    b.Navigation("IngredientUnits");

                    b.Navigation("Ingredients");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Pinula.Shared.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("RecipeUsers");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
